[features]
seeds = false
skip-lint = false
[programs.devnet]
myepicproject = "8YehNCR8UvUeFqiYuSVwoQ6xX25RjACGNzk2bQMEQS8y"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/benyam/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js"
